<?php
define('PACKAGES_TITLE',__('Manage Price Packages',DOMAIN));
define('ADD_A_PACKAGE_LINK',__('Add New Package',DOMAIN));
define('MONETIZATION_SETTINGS',__('Monetization Settings',DOMAIN));
define('ADD_NEW',__('Add New Package',DOMAIN));
define('ADD_NEW_DESC',__('Here are the currency settings where you can set the currency code, currency symbol and currency position for your domain',DOMAIN));
define('ADD_NEW_PACKAGE_DESC',__('A new package will be generated after you fill up the below information. These packages will allow you to charge the users to submit posts on your site',DOMAIN));
define('PACKAGE_LIST_DESC',__('A classic feature from Templatic which enables you to set different packages on your site. You need to set the <strong>currency</strong> in order to use this feature',DOMAIN));
define('YES',__('Yes',DOMAIN));
define('NO',__('No',DOMAIN));
define('ACTIVE',__('Active',DOMAIN));
define('INACTIVE',__('Inactive',DOMAIN));
define('REQUIRED_TEXT',__('required',DOMAIN));
define('PACKAGE_TITLE',__('Package Name',DOMAIN));
define('PACKAGE_NAME_DESC',__('This will be display as a package title in front end. ex. Summer Package',DOMAIN));
define('PER_POST_DESC',__('Enabling this will allow you to charge the users per each post submission',DOMAIN));
define('PER_SUBSCRIPTION_DESC',__('Pay per subscription enables you to allow the users to submit unlimited posts during their subscription period',DOMAIN));
define('PACKAGE_CATEGORIES',__('Select Categories',DOMAIN));
define('PACKAGE_CATEGORIES_DESC',__('This package will be display for the selected categories',DOMAIN));
define('PACKAGE_DESC_TITLE',__('Package Description',DOMAIN));
define('PACKAGE_DESC',__('In a few words, describe what this packages is about',DOMAIN));
define('SHOW_PACKAGE',__('Show Package',DOMAIN));
define('SHOW_PACKAGE_TITLE',__('Show Package even when no category is selected',DOMAIN));
define('SHOW_PACKAGE_DESC',__('This package will be display even when user does not select any category',DOMAIN));
define('SELECT_POST_TYPES',__('Select Post Type',DOMAIN));
define('POST_TYPE_DESC',__('This package will be enabled for the selected post type',DOMAIN));
define('PACKAGE_AMOUNT',__('Package Amount',DOMAIN));
define('PRICE_AMOUNT_DESC',__('Mention the package amount',DOMAIN));
define('BILLING_PERIOD',__('Billing Period',DOMAIN));
define('BILLING_PERIOD_DESC',__('Set the time period for this package',DOMAIN));
define('DAYS_TEXT',__('Days',DOMAIN));
define('MONTHS_TEXT',__('Months',DOMAIN));
define('YEAR_TEXT',__('Years',DOMAIN));
define('PACKAGE_STATUS',__('Package Status',DOMAIN));
define('PACKAGE_STATUS_DESC',__('Checking mark this will activate this package on your site',DOMAIN));
define('IS_RECURRING',__('Is Recurring',DOMAIN));
define('RECURRING_DESC',__('Selecting this option will enable you to charge the users automatically after the billing period gets over',DOMAIN));
define('CHARGE_USER',__('Charge users every',DOMAIN));
define('RECURRING_BILLING_PERIOD',__('Billing Period for Recurring package',DOMAIN));
define('RECURRING_BILLING_PERIOD_DESC',__('Set the time period for recurrence',DOMAIN));
define('RECURRING_BILLING_CYCLE',__('Billing Cycle',DOMAIN));
define('RECURRING_BILLING_CYCLE_DESC',__('This specifies the billing cycle for recurring package. Mention the number of times you want to repeat the recurring process',DOMAIN));
define('SETTINGS_FOR_FEATURED',__('Settings for Featured posts',DOMAIN));
define('SETTINGS_FOR_FEATURED_DESC',__('These settings are must if you want to charge the users for featured posts otherwise leave them blank',DOMAIN));
define('IS_FEATURED',__('Is Featured',DOMAIN));
define('FEATURED_STATUS_DESC',__('Checking mark on this will enable you to charge the users extra for featured posts',DOMAIN));
define('FEATURED_AMOUNT_HOME',__('Amount to be charged for Home page',DOMAIN));
define('FEATURED_AMOUNT_HOME_DESC',__('Mention the amount to charge extra for home page featured posts',DOMAIN));
define('FEATURED_AMOUNT_CAT',__('Amount to be charged for Category page',DOMAIN));
define('FEATURED_AMOUNT_CAT_DESC',__('Mention the amount to charge extra for category listing page featured posts',DOMAIN));
define('BACK_LINK_TEXT',__('Back to packages list',DOMAIN));
define('ACTION',__('Action',DOMAIN));
define('PACKAGE_DETAILS',__('Package Detail',DOMAIN));
define('EDIT_PACKAGE',__('Edit Package',DOMAIN));
define('DELETE_PACKAGE',__('Delete Package',DOMAIN));
define('NO_PACKAGE_AVAIL',__('You have not inserted any package yet',DOMAIN));
define('PACKAGE_TYPE',__('Pakcage Type',DOMAIN));
define('PAY_PER_POST',__('Pay per Post',DOMAIN));
define('PAY_PER_SUB',__('Pay per Subscription',DOMAIN));
define('LIMIT_NO_POST',__('Number of Posts',DOMAIN));
define('NO_POST_DESC',__('This will be submit the number of limited post on pay per Subscription.',DOMAIN));
define('VALIDITY_TEXT',__('Validity',DOMAIN));
define('PACKAGE_COST',__('Charges',DOMAIN));
define('PACKAGE_CYCLE',__('Recurring Charges',DOMAIN));
define('SELECT_PACKAGE_TEXT',__('Select a Package',DOMAIN));
define('CURRENCY_SYMB',__('Currency Symbol',DOMAIN));
define('CURRENCY_SYMB_DESC',__('You can specify the currency symbol here',DOMAIN));
define('CURRENCY_CODE',__('Currency Code',DOMAIN));
define('CURRENCY_CODE_DESC',__('You can specify the currency code here',DOMAIN));
define('CURRENCY_POS',__('Currency Position',DOMAIN));
define('CURRENCY_POS_DESC',__('You can set the currency position from here',DOMAIN));
define('SYMB_BFR_AMT',__('Symbol Before amount',DOMAIN));
define('SPACE_BET_BFR_AMT',__('Space between Before amount and Symbol',DOMAIN));
define('SYM_AFTR_AMT',__('Symbol After amount',DOMAIN));
define('SPACE_BET_AFTR_AMT',__('Space between After amount and Symbol',DOMAIN));
define('FEATURED_TITLE',__('Would you like to make this post Featured?',DOMAIN));
define('FEATURED_HOME',__('Make this post featured on Home page',DOMAIN));
define('FEATURED_CAT',__('Make this post featured on Category listing page',DOMAIN));
define('FEATURED_MSG_DESC',__('An additional charges will be applied to make this post featured on any of the pages',DOMAIN));
define('TOTAL_CHARGES_TEXT',__('Total Charges',DOMAIN));
define('FEATURE_HEAD_TITLE',__('Price settings for Featured listings',DOMAIN)); 
define('FEATURE_HEAD_NOTE',__('<p class="notes_spec">You might want to charge users extra amount for featured listings within this price package.</p> ',DOMAIN)); 
define('FEATURE_STATUS_NOTE',__('Activate/deactivate additional price settings for &raquofeatured&raquo listings.',DOMAIN)); 
define('FEATURE_AMOUNT_TITLE',__('Amount to be charged<br><small>(for featuring on homepage)</small>',DOMAIN)); 
define('FEATURE_AMOUNT_NOTE',__('This is the price you wish to charge extra for featuring a place or an event listing on the homepage. eg. 20',DOMAIN)); 
define('FEATURE_CAT_TITLE',__('Amount to be charged<br><small>(for featuring on categories page)</small>',DOMAIN)); 
define('FEATURE_CAT_NOTE',__('This is the price you wish to charge extra for a place or an event listing on category pages. eg. 12',DOMAIN)); 
define('STATUS_NOTE',__('This setting will activate / deactivate this price package.',DOMAIN));
define('RECENT_TRANSACTION_TEXT',__('Latest transactions',DOMAIN));

/*submit page price packages */
define('SUBMIT_LISTING_DAYS_TEXT',__('You are going to submit for %s days',DOMAIN));
define('ENTER_EVENT',__('1. Enter Event Listing Details',DOMAIN));
define('PREVIEW_EVENT',__('2. Preview Event &amp; Payment',DOMAIN));
define('SUCCESS_EVENT',__('3. Event Successful',DOMAIN));
define('FEATURED_H',__('Yes &sbquo; feature this listing on homepage.',DOMAIN));
define('FEATURED_C',__('Yes &sbquo; feature this listing on category pages.',DOMAIN));
define('FEATURED_H_EVENT',__('Yes &sbquo; feature this event on homepage.',DOMAIN));
define('FEATURED_C_EVENT',__('Yes &sbquo; feature this event on category pages.',DOMAIN));
define('TOTAL_TEXT',__('Total price as per your selection.',DOMAIN));
define('ORDER_STATUS_TITLE',__('Order Status',DOMAIN));

/* PAYMENT OPTIONS */
define('APPROVED_TEXT',__('Approved',DOMAIN));
define('PENDING_MONI',__('Pending',DOMAIN));
define('PAYMENT_SUCCESS_TITLE',__('Payment Success',DOMAIN));
define('BACK_TO_OREDR_TITLE',__('Back to Orders Listing',DOMAIN));
define('ORDER_STATUS_SAVE_MSG',__('Order status changed successfully',DOMAIN));
define('PAYMENT_SUCCESS_MSG',__('Thank you for joining us. Your payment is received and event is published.<br>Thank you for becoming our valued member.<br><br>You can edit this message from language.php file at root of theme folder.',DOMAIN));
define('INVALID_TRANSACTION_TITLE',__('Inavalid transation',DOMAIN));
define('INVALID_TRANSACTION_CONTENT',__('There is some error occured while transaction is being process, please try again.',DOMAIN));
define('AUTHENTICATION_CONTENT',__('Authentication fail, invalid transaction id generated.',DOMAIN));
define('PAY_CANCEL_MSG',__('Event Posting cancelled.<br><br>You can edit this message from language.php file at root of theme folder.',DOMAIN));
define('NEW_PAYMENT_GATEWAY_TITLE',__('Install New Payment Gateway',DOMAIN));
define('ORDER_UPDATE_TITLE',__('Update',DOMAIN));
define('MAIL_TO_FRIEND',__('Mail to a friend',DOMAIN));
define('SEND_INQUIRY',__('Send inquiry',DOMAIN));

/*Transaction Report*/ 
define('TRANSACTION_REPORT_TEXT',__('Transaction Report',DOMAIN));
define('BACK_TO_TRANSACTION_LINK',__('Back to transaction list',DOMAIN));
define('TRANSACTION_REPORT_DESC',__('Here you can view the transaction detail.',DOMAIN));
define('COLOR',__('Color',DOMAIN));
define('ORDER_CANCEL_TEXT',__('Cancel',DOMAIN));

/* MANAGE COUPONS */
define('COUPON_ST_DATE',__('Coupon Start Date',DOMAIN));
define('COUPON_ST_DATE_DESC',__('Mention coupon start date',DOMAIN));
define('COUPON_END_DATE',__('Coupon End Date',DOMAIN));
define('COUPON_END_DATE_DESC',__('Mention coupon end date. After this date, the coupon will be expired and not be applicable anymore',DOMAIN));
define('COUPON_CODE_DESC',__('Mention coupon code',DOMAIN));
define('COUPON_TYPE_DESC',__('Specify coupon type, the way you wish to calculate the discount amount',DOMAIN));
define('COUPON_AMOUNT_DESC',__('Specify coupon amount. This amount will be discounted as per coupon type you have selected',DOMAIN));
?>